"""add daily_seat_bookings table

Revision ID: 1666d0a980b9
Revises: 02ab2f8a2633
Create Date: 2026-06-18 03:59:09.687380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1666d0a980b9'
down_revision = '02ab2f8a2633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_seat_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(length=120), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booked_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seat_number', 'booking_date', name='uq_seat_per_day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_seat_bookings')
    # ### end Alembic commands ###
