"""add renewal request proposed dates

Revision ID: 20260821101124
Revises: f1a2b3c4d5e6
Create Date: 2026-08-21 10:11:24.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260821101124'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewal_requests', sa.Column('proposed_start_date', sa.Date(), nullable=True))
    op.add_column('renewal_requests', sa.Column('proposed_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renewal_requests', 'proposed_end_date')
    op.drop_column('renewal_requests', 'proposed_start_date')
    # ### end Alembic commands ###
